In [ ]:
%load_ext autoreload
%autoreload 2

In [1]:
from maskrcnn_benchmark.layers import (
    SigmoidFocalLoss,
    BinarySigmoidFocalLoss,
    SigmoidReducedFocalLoss,
    BinarySigmoidReducedFocalLoss,
)

In [2]:
import torch
print(torch.__version__)
import torch.nn.functional as F

1.1.0.dev20190511


In [34]:
logits = torch.tensor([.1, -.1])
print(logits)
targets = torch.tensor([1., 0.])
print(targets)
alpha = 0.25
gamma = 2.0
cutoff = 0.5

tensor([ 0.1000, -0.1000])
tensor([1., 0.])


In [35]:
fl_t = BinarySigmoidReducedFocalLoss([gamma], [alpha], [cutoff])
with torch.no_grad():
    print(fl_t(logits, targets))

tensor(0.7345)


In [39]:
bce_loss = F.binary_cross_entropy_with_logits(logits, targets, reduction='none')
pt = torch.exp(-bce_loss)
rf_loss = (pt < cutoff).float() * alpha * bce_loss \
        + (pt >= cutoff).float() * alpha * ((1-pt)/cutoff)**gamma * bce_loss
print(rf_loss)

tensor([0.1454, 0.1454])


In [ ]:
import numpy as np
import math

In [ ]:
def sigmoid(x):
    return 1 / (1 + math.exp(-x))
def fl(x, correct = True):
    print(x)
    sig = sigmoid(x) if correct else 1 - sigmoid(x)
    alph = alpha if correct else 1 -alpha
    print(sigmoid(x))
    print((1-sig)**gamma * np.log(sig))
    return - alph * ((1-sig)**gamma) * np.log(sig)

In [ ]:
logit = [.5]
print(logit)
target = 0
fls = [fl(a, (i == target)) for i,a in enumerate(logit)]
print(fls)